services:
  api:
    build: .
    restart: always
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: "nouchka/sqlite3"
    volumes:
      - sqlite_data:/data
    restart: always

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    restart: always
    depends_on:
      - api

volumes:
  sqlite_data:
